### ISSUE TITLE
Unable to use - Windows 11

### ISSUE THREAD

**Issue by spacechoc** [NotEvenIndian/CSLapse#1]
I have Windows 11 and every time I try to open the python file it pops up with a black window and almost instantly closes. Am I doing something wrong? I have unzipped the files and moved them to the CSLapse folder within Cities.

**Comment by NotEvenIndian** [comment]
I'm sorry to hear that, the problem is not necessarily on your side. Unfortunately, I have not yet implemented logging which makes it extremely hard to diagnose the issue. Implementing t will be my naxt main priority which may take up to a few weeks, but until then there's not much I can do. I'll get back to you as soo as I'm ready.

**Comment by NotEvenIndian** [comment]
Hello, it was simpler than I expected. Version 1.1.0 is available under releases with logging. If you could try running that and upload the cslapse.log file, I could possibly diagnose the issue.
The log files include full path to your files. If you feel uncomfortable sharing some details (your username for example), you can search and replace them in the log file before uploading it.
Also make sure that you have a 64 bit processor. You can check this in Start > Settings > System > About.

Are you trying to executable the .exe file or the .py file? The latter wont work by itself, for that you need the python interpreter. But the .exe file has the same functionality and can run natively.

**Comment by spacechoc** [comment]
Thank you for your swift reply,
The folder does not appear to contain an exe file.
![Screenshot (321)](https://user-images.githubusercontent.com/123671076/216138787-037079ab-b432-45a3-820a-c9cca0fd367d.png)
Am I just being stupid or do I have to do something to get an exe?

**Comment by NotEvenIndian** [comment]
Yes, the exe is not tracked using git. You don't have to clone the repo in order to get it, you can directly download it from [releases](https://github.com/NotEvenIndian/CSLapse/releases).

**Comment by spacechoc** [comment]
works fine now thanks
